name: .NET

# Updated: 2023-02-10

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private references
        uses: actions/checkout@v3.5.0
        with:
          repository: CTristan/lobotomy-corporation-mods-references
          token: ${{ secrets.PRIVATE_REFERENCES_TOKEN }}
          persist-credentials: false

      - name: Create project directories
        run: |
          mkdir BaseMods
          cd BaseMods
          mkdir src
          cd src
          mkdir lobotomy-corporation-mods
          cd lobotomy-corporation-mods

      - name: Checkout main repository
        uses: actions/checkout@v3.5.0
        with:
          path: BaseMods/src/lobotomy-corporation-mods

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Restore dependencies
        run: dotnet restore BaseMods/src/lobotomy-corporation-mods/LobotomyCorporationMods.sln

      - name: Build
        run: dotnet build --no-restore BaseMods/src/lobotomy-corporation-mods/LobotomyCorporationMods.sln

      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput="./coverage.opencover.xml" /p:CoverletOutputFormat=opencover --no-build --verbosity normal BaseMods/src/lobotomy-corporation-mods/LobotomyCorporationMods.sln

      # Coverage reports specify the .NET Framework 4.8 file since the test runner doesn't work with .NET Framework 3.5

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          root_dir: BaseMods/src/lobotomy-corporation-mods
          files: LobotomyCorporationMods.Test/coverage.opencover.net48.xml

      - name: Upload coverage reports to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: BaseMods/src/lobotomy-corporation-mods/LobotomyCorporationMods.Test/coverage.opencover.net48.xml
